services:
  - type: web
    name: mind-mentor-backend
    env: node
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_API_KEY_RAG
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
